routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'guest'], function() {
    Route::get('/login', 'UsersController@login')->name('login');
    Route::post('/login', 'UsersController@loginAuth')->name('loginAuth');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function() {
    Route::get('/', 'DashboardController@index');
    Route::get('/logout', 'UsersController@logout')->name('logout');
    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@update')->name('settings.update');
    Route::resource('/feedbacks', 'FeedbacksController');
    Route::resource('/pages', 'PagesController');
    Route::resource('/services', 'ServicesController');
    Route::resource('/users', 'UsersController');
});

Route::post('/send', 'HomeController@send');

Route::get('/{parent}', 'HomeController@page');
Route::get('/{parent}/{child}', 'HomeController@page');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Service extends Model
{
    protected $fillable = [
        'name', 'price'
    ];

    public static function add($fields)
    {
        $site = new static;

        $site->fill($fields);
        $site->save();

        return $site;
    }

    public function edit($fields)
    {
        $this->fill($fields);
        $this->save();
    }

    public function remove()
    {
        $this->removeImage('image');
        $this->delete();
    }

    public function uploadImage($image, $field)
    {
        if ($image == null) return;

        $this->removeImage($field);
        $filename = str_random(10) . '.' . $image->extension();
        $image->storeAs('public/services', $filename);
        $this->$field = $filename;
        $this->save();
    }

    public function removeImage($field)
    {
        if ($this->$field != null) Storage::delete('public/services/' . $this->$field);
    }

    public function getImage($field)
    {
        if ($this->$field == null) return '/images/no_image_320x240.jpg';
        else return Storage::url('services/' . $this->$field);
    }
}

app/Http/Controllers/Admin/ServicesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Service;

class ServicesController extends Controller
{
    public function index()
    {
        $services = Service::all();

        return view('admin.services.index', compact('services'));
    }

    public function create()
    {
        return view('admin.services.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'image' => 'nullable|image'
        ]);

        $service = Service::add($request->all());
        $service->uploadImage($request->file('image'), 'image');

        return redirect()->route('services.index');
    }

    public function edit($id)
    {
        $service = Service::find($id);

        return view('admin.services.edit', compact('service'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'image' => 'nullable|image'
        ]);

        $service = Service::find($id);
        $service->edit($request->all());
        $service->uploadImage($request->file('image'), 'image');

        return redirect()->route('services.index');
    }

    public function destroy($id)
    {
        Service::find($id)->remove();
    }
}

resources/views/admin/services/create.blade.php
@extends('admin.layout', ['title' => 'Новая услуга - Добавление'])

@section('content')
{{ Form::open(['route' => 'services.store', 'files' => true]) }}
    <div class="card card-secondary">
        <div class="card-header">
            <h3 class="card-title">Информация</h3>
        </div>
        <div class="card-body">
            @include('admin.errors')
            <div class="row">
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Название</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Изображение</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="file" class="form-control-file" name="image">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Цена</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="text" class="form-control" name="price" value="{{ old('price') }}">
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn bg-gradient-success">Сохранить</button>
            <a href="{{ route('services.index') }}" class="btn bg-gradient-secondary">Отменить</a>
        </div>
    </div>
{{ Form::close() }}
@endsection

resources/views/admin/services/edit.blade.php
@extends('admin.layout', ['title' => $service->name . ' - Редактирование'])

@section('content')
{{ Form::open(['route' => ['services.update', $service->id], 'method' => 'put', 'files' => true]) }}
    <div class="card card-secondary">
        <div class="card-header">
            <h3 class="card-title">Информация</h3>
        </div>
        <div class="card-body">
            @include('admin.errors')
            <div class="row">
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Название</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="text" class="form-control" name="name" value="{{ $service->name }}">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Изображение</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <p><img src="{{ $service->getImage('image') }}" alt="" class="preview-image"></p>
                        <input type="file" class="form-control-file" name="image">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Цена</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="text" class="form-control" name="price" value="{{ $service->price }}">
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn bg-gradient-success">Сохранить</button>
            <a href="{{ route('services.index') }}" class="btn bg-gradient-secondary">Отменить</a>
        </div>
    </div>
{{ Form::close() }}
@endsection

resources/views/admin/services/index.blade.php
@extends('admin.layout', ['title' => 'Услуги и цены'])

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <a href="{{ route('services.create') }}" class="btn bg-gradient-success">Добавить</a>
            </div>
            <div class="card-body">
                <table id="list" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Название</th>
                            <th>Изображение</th>
                            <th>Цена</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($services as $service)
                        <tr>
                            <td>{{ $service->id }}</td>
                            <td><a href="{{ route('services.edit', $service->id) }}">{{ $service->name }}</a></td>
                            <td><img src="{{ $service->getImage('image') }}" alt="" class="preview-image"></td>
                            <td>{{ $service->price }}</td>
                            <td>
                                <a href="{{ route('services.edit', $service->id) }}" class="btn bg-gradient-warning"
                                    title="Изменить"
                                >
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a href="#" class="btn bg-gradient-danger js-remove"
                                    data-url="{{ route('services.destroy', $service->id) }}"
                                    title="Удалить"
                                >
                                    <i class="fas fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection