routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'guest'], function() {
    Route::get('/login', 'UsersController@login')->name('login');
    Route::post('/login', 'UsersController@loginAuth')->name('loginAuth');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function() {
    Route::get('/', 'DashboardController@index');
    Route::get('/logout', 'UsersController@logout')->name('logout');
    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@update')->name('settings.update');
    Route::resource('/feedbacks', 'FeedbacksController');
    Route::resource('/pages', 'PagesController');
    Route::resource('/services', 'ServicesController');
    Route::resource('/users', 'UsersController');
});

Route::post('/send', 'HomeController@send');

Route::get('/{parent}', 'HomeController@page');
Route::get('/{parent}/{child}', 'HomeController@page');

resources/views/admin/dashboard.blade.php
@extends('admin.layout', ['title' => 'Панель администратора'])

@section('content')
<p class="lead">Здравствуйте, {{ $user->name }}!</p>
@endsection

resources/views/admin/errors.blade.php
@if ($errors->any())
<div class="alert alert-danger" role="alert">
    <ul class="list-unstyled mb-0">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ $title }}</title>
    <meta name="description" content="description">
    <meta name="keywords" content="keywords">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="/css/admin.css?<?=time()?>" rel="stylesheet">
    <link href="/css/main.css?<?=time()?>" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">
<div class="wrapper">
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#" class="nav-link" data-widget="pushmenu"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="/admin" class="nav-link">Главная</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{{ route('settings.index') }}" class="nav-link">Настройки</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{{ route('services.index') }}" class="nav-link">Услуги и цены</a>
            </li>
            <li class="nav-item d-none">
                <a href="{{ route('feedbacks.index') }}" class="nav-link">Веб-формы</a>
            </li>
        </ul>
        <a href="{{ route('logout') }}" class="ml-auto mr-3">Выйти</a>
    </nav>
    @include('admin.sidebar')
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <h1 class="mb-2">{{ $title }}</h1>
            </div>
        </section>
        <div class="content">
            <div class="container-fluid">
                @yield('content')
            </div>
        </div>
    </div>
    <footer class="main-footer">
        &copy; {{ $site->name }}, 2020. Все права защищены.
    </footer>
</div>
<script src="/js/admin.js?<?=time()?>"></script>
<script src="/js/main.js?<?=time()?>"></script>
</body>
</html>

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Авторизация</title>
    <meta name="description" content="description">
    <meta name="keywords" content="keywords">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="/css/admin.css?<?=time()?>" rel="stylesheet">
    <link href="/css/main.css?<?=time()?>" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="/">{{ $site->name }}</a>
    </div>
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Пожалуйста, авторизуйтесь</p>
            {{ Form::open(['route' => 'loginAuth']) }}
                @if (session('error'))
                <div class="alert alert-danger">
                    <p class="mb-0">{{ session('error') }}</p>
                </div>
                @endif
                @include('admin.errors')
                <div class="input-group mb-3">
                    <input type="text" name="email" class="form-control" placeholder="E-mail">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" name="password" class="form-control" placeholder="Пароль">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            {{ Form::checkbox('remember', 1, null, ['id' => 'checkbox-remember']) }}
                            <label for="checkbox-remember">Запомнить меня</label>
                        </div>
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn bg-gradient-primary btn-block">Войти</button>
                    </div>
                </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
<script src="/js/admin.js?<?=time()?>"></script>
<script src="/js/main.js?<?=time()?>"></script>
</body>
</html>

resources/views/admin/settings.blade.php
@extends('admin.layout', ['title' => 'Настройки'])

@section('content')
{{ Form::open(['route' => 'settings.update', 'files' => true]) }}
    <div class="card card-secondary">
        <div class="card-header">
            <h3 class="card-title">Информация</h3>
        </div>
        <div class="card-body">
            @include('admin.errors')
            <div class="row">
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Название</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="text" class="form-control" name="name" value="{{ $site->name }}">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">E-mail получателя писем</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="text" class="form-control" name="mail_to" value="{{ $site->mail_to }}">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Логотип</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <p><img src="{{ $site->getImage('logo') }}" alt="" class="preview-image"></p>
                        <input type="file" class="form-control-file" name="logo">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Адрес</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="text" class="form-control" name="address" value="{{ $site->address }}">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Телефон</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="text" class="form-control" name="phone" value="{{ $site->phone }}">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">E-mail</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <input type="text" class="form-control" name="email" value="{{ $site->email }}">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Баннер (Изображение)</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <p><img src="{{ $site->getImage('banner_image') }}" alt="" class="preview-image"></p>
                        <input type="file" class="form-control-file" name="banner_image">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">Баннер (Текст)</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <textarea class="form-control js-editor" name="banner_text">{{ $site->banner_text }}</textarea>
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">О компании (Изображение)</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <p><img src="{{ $site->getImage('about_us_image') }}" alt="" class="preview-image"></p>
                        <input type="file" class="form-control-file" name="about_us_image">
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">О компании (Текст)</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <textarea class="form-control js-editor" name="about_us_text">{{ $site->about_us_text }}</textarea>
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="text-bold text-md-right mt-1">О компании (Внизу)</p>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <textarea class="form-control" name="footer_text" rows="2">{{ $site->footer_text }}</textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-md-8 offset-md-4">
                    <button type="submit" class="btn bg-gradient-success">Сохранить</button>
                    <a href="/admin" class="btn bg-gradient-secondary">Отменить</a>
                </div>
            </div>
        </div>
    </div>
{{ Form::close() }}
@endsection

resources/views/admin/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="/admin" class="brand-link">
        <i class="fas fa-balance-scale my-1 mr-2 ml-3"></i>
        <span class="brand-text font-weight-light">{{ $site->name }}</span>
    </a>
    <div class="sidebar">
        <div class="user-panel pb-3 mt-3 mb-3 d-flex">
            <div class="image">
                <img src="/images/AdminLTE/user2-160x160.jpg" alt="" class="img-circle elevation-2">
            </div>
            <div class="info">
                <a href="/admin" class="d-block">{{ $user->name }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @foreach ($menu as $item)
                <li class="nav-item has-treeview">
                    <a href="{{ $item['href'] }}" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>{{ $item['name'] }}<i class="fas fa-angle-left right"></i></p>
                    </a>
                    @if ($item['childs'])
                    <ul class="nav nav-treeview">
                        @foreach ($item['childs'] as $child)
                        <li class="nav-item">
                            <a href="{{ route('pages.edit', $child['id']) }}" class="nav-link">
                                <i class="nav-icon far fa-circle"></i>
                                <p>{{ $child['name'] }}</p>
                            </a>
                        </li>
                        @endforeach
                    </ul>
                    @endif
                </li>
                @endforeach
                <li class="nav-item has-treeview">
                    <a href="{{ route('pages.create') }}" class="nav-link active">
                        <i class="nav-icon fas fa-plus"></i>
                        <p>Добавить</p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>