routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'guest'], function() {
    Route::get('/login', 'UsersController@login')->name('login');
    Route::post('/login', 'UsersController@loginAuth')->name('loginAuth');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function() {
    Route::get('/', 'DashboardController@index');
    Route::get('/logout', 'UsersController@logout')->name('logout');
    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@update')->name('settings.update');
    Route::resource('/feedbacks', 'FeedbacksController');
    Route::resource('/pages', 'PagesController');
    Route::resource('/services', 'ServicesController');
    Route::resource('/users', 'UsersController');
});

Route::post('/send', 'HomeController@send');

Route::get('/{parent}', 'HomeController@page');
Route::get('/{parent}/{child}', 'HomeController@page');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'email'
    ];

    protected $hidden = [
        'password', 'remember_token'
    ];

    protected $casts = [
        'email_verified_at' => 'datetime'
    ];

    public static function add($fields)
    {
        $user = new static;

        $user->fill($fields);
        $user->save();

        return $user;
    }

    public function edit($fields)
    {
        $this->fill($fields);
        $this->save();
    }

    public function remove()
    {
        $this->delete();
    }

    public function generatePassword($password)
    {
        if ($password != null)
        {
            $this->password = bcrypt($password);
            $this->save();
        }
    }

    public function setStatus($value)
    {
        if ($value == 1) $this->status = 1;
        else $this->status = 0;

        $this->save();
    }

    public function isActive()
    {
        if ($this->status == 1) return 'Да';
        else return 'Нет';
    }

    public function isAdmin()
    {
        if ($this->admin == 1) return 'Да';
        else return 'Нет';
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use App\User;
use Auth;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    public function create()
    {
        return view('admin.users.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required'
        ]);

        $user = User::add($request->all());
        $user->generatePassword($request->get('password'));
        $user->setStatus(1);

        return redirect()->route('users.index');
    }

    public function edit($id)
    {
        $user = User::find($id);

        return view('admin.users.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => ['required', 'email', Rule::unique('users')->ignore($id)]
        ]);

        $user = User::find($id);
        $user->edit($request->all());
        $user->generatePassword($request->get('password'));
        $user->setStatus($request->get('status'));

        return redirect()->route('users.index');
    }

    public function destroy($id)
    {
        User::find($id)->remove();
    }

    public function login()
    {
        return view('admin.login');
    }

    public function loginAuth(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email',
            'password' => 'required'
        ]);

        $auth = Auth::attempt([
            'email' => $request->get('email'),
            'password' => $request->get('password')
        ]);

        if ($auth) return redirect('/admin');
        else return redirect()->back()->with('error', 'Неправильный логин или пароль.');
    }

    public function logout()
    {
        Auth::logout();

        return redirect()->route('login');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layout', ['title' => 'Новый пользователь'])

@section('content')
{{ Form::open(['route' => 'users.store']) }}
    <div class="row">
        <div class="col-md-6">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Добавление</h3>
                </div>
                <div class="card-body">
                    @include('admin.errors')
                    <div class="form-group">
                        <label>Имя</label>
                        <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                    </div>
                    <div class="form-group">
                        <label>E-mail</label>
                        <input type="text" class="form-control" name="email" value="{{ old('email') }}">
                    </div>
                    <div class="form-group">
                        <label>Пароль</label>
                        <input type="password" class="form-control" name="password">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn bg-gradient-success">Сохранить</button>
                    <a href="{{ route('users.index') }}" class="btn bg-gradient-secondary">Отменить</a>
                </div>
            </div>
        </div>
    </div>
{{ Form::close() }}
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layout', ['title' => $user->name])

@section('content')
{{ Form::open(['route' => ['users.update', $user->id], 'method' => 'put']) }}
    <div class="row">
        <div class="col-md-6">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Редактирование</h3>
                </div>
                <div class="card-body">
                    @include('admin.errors')
                    <div class="form-group">
                        <div class="icheck-primary d-inline">
                            {{ Form::checkbox('status', 1, $user->status, ['id' => 'checkbox-status']) }}
                            <label for="checkbox-status">Активность</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Имя</label>
                        <input type="text" class="form-control" name="name" value="{{ $user->name }}">
                    </div>
                    <div class="form-group">
                        <label>E-mail</label>
                        <input type="text" class="form-control" name="email" value="{{ $user->email }}">
                    </div>
                    <div class="form-group">
                        <label>Пароль</label>
                        <input type="password" class="form-control" name="password">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn bg-gradient-success">Сохранить</button>
                    <a href="{{ route('users.index') }}" class="btn bg-gradient-secondary">Отменить</a>
                </div>
            </div>
        </div>
    </div>
{{ Form::close() }}
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layout', ['title' => 'Пользователи'])

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <a href="{{ route('users.create') }}" class="btn bg-gradient-success">Добавить</a>
            </div>
            <div class="card-body">
                <table id="list" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>E-mail</th>
                            <th>Активность</th>
                            <th>Администратор</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                        <tr>
                            <td>{{ $user->id }}</td>
                            <td><a href="{{ route('users.edit', $user->id) }}">{{ $user->name }}</a></td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->isActive() }}</td>
                            <td>{{ $user->isAdmin() }}</td>
                            <td>
                                <a href="{{ route('users.edit', $user->id) }}" class="btn bg-gradient-warning"
                                    title="Изменить"
                                >
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a href="#" class="btn bg-gradient-danger js-remove"
                                    data-url="{{ route('users.destroy', $user->id) }}"
                                    title="Удалить"
                                >
                                    <i class="fas fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection