routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'guest'], function() {
    Route::get('/login', 'UsersController@login')->name('login');
    Route::post('/login', 'UsersController@loginAuth')->name('loginAuth');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function() {
    Route::get('/', 'DashboardController@index');
    Route::get('/logout', 'UsersController@logout')->name('logout');
    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@update')->name('settings.update');
    Route::resource('/feedbacks', 'FeedbacksController');
    Route::resource('/pages', 'PagesController');
    Route::resource('/services', 'ServicesController');
    Route::resource('/users', 'UsersController');
});

Route::post('/send', 'HomeController@send');

Route::get('/{parent}', 'HomeController@page');
Route::get('/{parent}/{child}', 'HomeController@page');

resources/views/admin/pages/create.blade.php
@extends('admin.layout', ['title' => 'Новая страница - Добавление'])

@section('content')
{{ Form::open(['route' => 'pages.store', 'files' => true]) }}
    <div class="row">
        <div class="col-md-6">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Информация</h3>
                </div>
                <div class="card-body">
                    @include('admin.errors')
                    <div class="form-group">
                        <div class="icheck-primary">
                            {{ Form::checkbox('status', 1, true, ['id' => 'checkbox-status']) }}
                            <label for="checkbox-status">Активность</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Название</label>
                        <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                    </div>
                    <div class="form-group">
                        <label>Раздел</label>
                        {{ Form::select('parent_id', $pages, null, ['class' => 'form-control js-select']) }}
                    </div>
                    <div class="form-group">
                        <label>Сортировка</label>
                        <input type="text" class="form-control" name="sort" value="500">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Мета-теги</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>Заголовок браузера</label>
                        <input type="text" class="form-control" name="seo_title" value="{{ old('seo_title') }}">
                    </div>
                    <div class="form-group">
                        <label>Мета Описание</label>
                        <textarea class="form-control" name="seo_description" rows="2">{{ old('seo_description') }}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Ключевые слова</label>
                        <input type="text" class="form-control" name="seo_keywords" value="{{ old('seo_keywords') }}">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Контент</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <textarea class="form-control js-editor" name="content">{{ old('content') }}</textarea>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn bg-gradient-success">Сохранить</button>
                    <a href="{{ route('pages.index') }}" class="btn bg-gradient-secondary">Отменить</a>
                </div>
            </div>
        </div>
    </div>
{{ Form::close() }}
@endsection

resources/views/admin/pages/edit.blade.php
@extends('admin.layout', ['title' => $page->name . ' - Редактирование'])

@section('content')
{{ Form::open(['route' => ['pages.update', $page->id], 'method' => 'put', 'files' => true]) }}
    <div class="row">
        <div class="col-md-6">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Информация</h3>
                </div>
                <div class="card-body">
                    @include('admin.errors')
                    <div class="form-group">
                        <div class="icheck-primary">
                            {{ Form::checkbox('status', 1, true, ['id' => 'checkbox-status']) }}
                            <label for="checkbox-status">Активность</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Название</label>
                        <input type="text" class="form-control" name="name" value="{{ $page->name }}">
                    </div>
                    <div class="form-group">
                        <label>Символьный код</label>
                        <input type="text" class="form-control" name="code" value="{{ $page->code }}">
                    </div>
                    <div class="form-group">
                        <label>Раздел</label>
                        {{ Form::select('parent_id', $pages, $page->parent_id, ['class' => 'form-control js-select']) }}
                    </div>
                    <div class="form-group">
                        <label>Сортировка</label>
                        <input type="text" class="form-control" name="sort" value="{{ $page->sort }}">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Мета-теги</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>Заголовок браузера</label>
                        <input type="text" class="form-control" name="seo_title" value="{{ $page->seo_title }}">
                    </div>
                    <div class="form-group">
                        <label>Мета Описание</label>
                        <textarea class="form-control" name="seo_description" rows="2">{{ $page->seo_description }}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Ключевые слова</label>
                        <input type="text" class="form-control" name="seo_keywords" value="{{ $page->seo_keywords }}">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Контент</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <textarea class="form-control js-editor" name="content">{{ $page->content }}</textarea>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn bg-gradient-success">Сохранить</button>
                    <a href="{{ route('pages.index') }}" class="btn bg-gradient-secondary">Отменить</a>
                </div>
            </div>
        </div>
    </div>
{{ Form::close() }}
@endsection

resources/views/admin/pages/index.blade.php
@extends('admin.layout', ['title' => 'Страницы сайта'])

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <a href="{{ route('pages.create') }}" class="btn bg-gradient-success">Добавить</a>
            </div>
            <div class="card-body">
                <table id="list" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Название</th>
                            <th>Символьный код</th>
                            <th>Сортировка</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($pages as $page)
                        <tr>
                            <td>{{ $page->id }}</td>
                            <td><a href="{{ route('pages.edit', $page->id) }}">{{ $page->name }}</a></td>
                            <td>{{ $page->code }}</td>
                            <td>{{ $page->sort }}</td>
                            <td>
                                <a href="{{ route('pages.edit', $page->id) }}" class="btn bg-gradient-warning"
                                    title="Изменить"
                                >
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a href="#" class="btn bg-gradient-danger js-remove"
                                    data-url="{{ route('pages.destroy', $page->id) }}"
                                    title="Удалить"
                                >
                                    <i class="fas fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection